knpu_oauth2_client:
  clients:
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
    github_main:
      type: github
      client_id: '%env(OAUTH_GITHUB_ID)%'
      client_secret: '%env(OAUTH_GITHUB_SECRET)%'
      #на этот роут редиректит гитхаб когда пользователь аутентифицируется там
      redirect_route: oauth.github_check
      redirect_params: { }
    github_attach:
      type: github
      client_id: '%env(OAUTH_GITHUB_ID)%'
      client_secret: '%env(OAUTH_GITHUB_SECRET)%'
      redirect_route: profile.oauth.github_check
      redirect_params: { }